name: Build CMake Project
run-name: Build ${{ inputs.cmake-preset }} ${{ inputs.msvc-toolkit }}

on:
  workflow_call:
    inputs:
      cmake-preset:
        required: true
        type: string
      upload-artifact-dll:
        required: false
        type: string
        default: false
      upload-artifact-vdf:
        required: false
        type: string
        default: false
      msvc-toolkit:
        required: false
        type: string
        default: 14.39
      project-version:
        required: false
        type: string
        default: false

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x86
          toolset: ${{ inputs.msvc-toolkit }}
          export-path-to-vcvarsall: VCVARSALL
      - name: Set project version
        if: ${{ inputs.project-version != 'false' }}
        env:
          PROJECT_VERSION: ${{ inputs.project-version }}
        run: |
          $version = $env:PROJECT_VERSION
          $cmakeVersion = $version -replace "([^0-9\.]+)",""
          $output = @'
          set(PROJECT_VERSION "{version}" CACHE STRING "" FORCE)
          set(PROJECT_VERSION_CMAKE "{cmake}" CACHE STRING "" FORCE)
          '@
          $output = $output -replace "{version}",$version
          $output = $output -replace "{cmake}",$cmakeVersion
          Set-Content -Path Configuration.override.cmake -Value $output
      - name: CMake Configure
        run: cmake --preset ${{ inputs.cmake-preset }}
      - name: CMake Build
        run: cmake --build out/build/${{ inputs.cmake-preset }} --target BuildVDF -j 16
      - name: CMake Install
        run: cmake --install out/build/${{ inputs.cmake-preset }} --prefix out/install/${{ inputs.cmake-preset }}
      - name: Archive DLL
        if: ${{ inputs.upload-artifact-dll != 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload-artifact-dll }}
          path: |
            out/install/${{ inputs.cmake-preset }}/bin/*.dll
            out/install/${{ inputs.cmake-preset }}/bin/Signatures/*.tsv
      - name: Archive VDF
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-artifact-vdf != 'false' }}
        with:
          name: ${{ inputs.upload-artifact-vdf }}
          path: out/install/${{ inputs.cmake-preset }}/bin/*.vdf